#!/bin/bash

endGridId=0 #inclusive
: ${queueName=teaching}
: ${ppn=16}
: ${configDir=./gridSearchConfigs/}
: ${globalOutDir=./gs_out/}

prog="./src/GA/bin/elfin"
jobCount=0
for gridId in $(seq 0 $endGridId); do
	#Each config ID can have multiple benchmarks attached
	bmConfigs=($(ls $configDir/*_"$gridId"_*\.json))

	for bmConfig in "${bmConfigs[@]}"; do
		cmd="$prog -s $bmConfig"
        gsOutDir=${bmConfig/$configDir/$globalOutDir}
        gsOutDir=${gsOutDir/\.json/'/'}
        cmdDir=$gsOutDir/cmd

        mkdir -p $gsOutDir

        echo "cd $HOME/src/elfin" > $cmdDir
        echo $cmd >> $cmdDir

        echo cmd is $cmd
        echo gsOutDir is $gsOutDir

		jobCount=$((jobCount + 1))
		echo Sending job "#$jobCount"
        #qsub -N elfin_omp -joe -o $gsOutDir/log -q $queueName -l nodes=1:ppn=$ppn,walltime=00:30:00 "$cmdDir"
    done

done